kind: Secret
apiVersion: v1
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "image-pull-secret.fullname" . }}
data:
  .dockerconfigjson:
{{ tpl (.Files.Get "src/dockerconfig.json.tpl") . | b64enc | indent 4 }}
